version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name:  zen-drawer-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - zen-drawer-db-data:/var/lib/postgresql/data

volumes:
   zen-drawer-db-data:
